name: ci
on: push
jobs:
  # example running all tests on a single machine
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        
      - name: Install dependencies 📦
        run: npm install   

      - name: Run split Cypress tests 🧪
        uses: cypress-io/github-action@v5

  # example splitting all tests across GitHub machines
  test-random-order:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install dependencies 📦
        run: npm install   

      - name: Run random order Cypress E2E tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        # using operating system process environment variables
        env:
          SPEC: "./rodri-e2e/test-file/e2e/**/*.cy.ts"
          SPLIT_RANDOM_SEED: 42
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: 'cypress-split'

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report ${{ strategy.job-index }}
          path: ./dist/cypress/report/
