name: ci
on: push

jobs:
  prepare: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-cypress
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-node-cypress
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'      
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

  test-random-order:
    needs: prepare
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-cypress
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-node-cypress

      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'  
          
      - name: Run random order Cypress E2E tests 🧪
        uses: cypress-io/github-action@v6
        with:
            install: false
            exclude: "rodri-e2e/test-file/e2e/testFolder"
        env:
            SPLIT: ${{ strategy.job-total }}
            SPLIT_INDEX: ${{ strategy.job-index }}
            SPLIT_FILE: '${{ inputs.split-file }}'
            SKIP_SPEC: '${{ inputs.skip-spec }}'
            DEBUG: 'cypress-split'
            grepTags: config
