name: ci
on: push
jobs:
  # example splitting all tests across GitHub machines
  test-random-order:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Install dependencies 📦
        run: npm install   

      - name: Run random order Cypress E2E tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        # using operating system process environment variables
        env:
          SPEC: "./rodri-e2e/test-file/e2e/*.cy.js"
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          DEBUG: 'cypress-split'

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report ${{ strategy.job-index }}
          path: ./dist/cypress/report/

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v2
        with:
          repository: RodrigoConde1/UiExam
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          path: test
          ref: main
          # Si necesitas una rama específica, puedes descomentar la siguiente línea y reemplazar <branch_name> con el nombre de tu rama
          # ref: <branch_name>
      
      - name: Install dependencies 📦
        run: cd test && npm install
      
      - name: Run tests
        run: cd test && npm test --spec "**/demoqa.features""
      
